### PR TITLE
Make more compatible with windows

### PR DESCRIPTION
**Pull request by garhbod**
Change a few path functions to make it more compatible with windows. Remove redundant output path handling also

Also could you update the version for composer so that the latest fixes are being used

### CODE REVIEW

**Comment by MisterDuval** [comment]
+1

**Comment by heiglandreas** [comment]
Thanks for the PullRequest. As I‘m on holiday ATM it
will take a day or two until I get around to actually getting some stuff done, but I will definitely see to it to get this fixed ASAP

**Comment by garhbod** [comment]
Okay @heiglandreas Let me know how it goes.

**Comment by heiglandreas** [comment]
Hey garhbod. Thanks for your PullRequest! I didn't merge it but took the content and implemented it in a slightly different way in #12. With the new release (coming every minute now) you should be able to run the library on windows as well.

Thanks for your input!

**Comment by garhbod** [comment]
Thanks @heiglandreas updated composer with your latest and everything is working fine

**Pull request closed without merging**
